In [1]:
import numpy as np

scalar = 5
print(f"Scalar: {scalar}")

Scalar: 5


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix:\n{matrix}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
def function(x):
    return x**2 + 2*x + 1

x = np.linspace(-10, 10, 100)
y = function(x)
gradient = np.gradient(y, x)

print(f"Gradient at each point:\n{gradient}")

Gradient at each point:
[-17.7979798  -17.5959596  -17.19191919 -16.78787879 -16.38383838
 -15.97979798 -15.57575758 -15.17171717 -14.76767677 -14.36363636
 -13.95959596 -13.55555556 -13.15151515 -12.74747475 -12.34343434
 -11.93939394 -11.53535354 -11.13131313 -10.72727273 -10.32323232
  -9.91919192  -9.51515152  -9.11111111  -8.70707071  -8.3030303
  -7.8989899   -7.49494949  -7.09090909  -6.68686869  -6.28282828
  -5.87878788  -5.47474747  -5.07070707  -4.66666667  -4.26262626
  -3.85858586  -3.45454545  -3.05050505  -2.64646465  -2.24242424
  -1.83838384  -1.43434343  -1.03030303  -0.62626263  -0.22222222
   0.18181818   0.58585859   0.98989899   1.39393939   1.7979798
   2.2020202    2.60606061   3.01010101   3.41414141   3.81818182
   4.22222222   4.62626263   5.03030303   5.43434343   5.83838384
   6.24242424   6.64646465   7.05050505   7.45454545   7.85858586
   8.26262626   8.66666667   9.07070707   9.47474747   9.87878788
  10.28282828  10.68686869  11.09090909  11.49494949  

In [7]:
vector = np.array([1, 2, 3])
print(f"Vector: {vector}")

Vector: [1 2 3]


In [9]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Tensor:\n{tensor}")

Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
matrix = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

Eigenvalues: [3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [17]:
# Norms
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])

vector_norm = np.linalg.norm(vector)
matrix_norm = np.linalg.norm(matrix)

print(f"Vector Norm: {vector_norm}")
print(f"Matrix Norm: {matrix_norm}")

# Eigen Decomposition
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

Vector Norm: 3.7416573867739413
Matrix Norm: 5.477225575051661
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
